CREATE table POVOLANI (
    POVOLANI_ID NUMBER NOT NULL,
    NAZEV       VARCHAR2(50) NOT NULL,
    constraint  POVOLANI_PK primary key (POVOLANI_ID)
);

CREATE table KRAJE (
    KRAJE_ID   NUMBER NOT NULL,
    NAZEV      VARCHAR2(50) NOT NULL,
    constraint  KRAJE_PK primary key (KRAJE_ID)
);

CREATE table OTAZKY (
    OTAZKY_ID   NUMBER NOT NULL,
    TEXT      VARCHAR2(500) NOT NULL,
    constraint  OTAZKY_PK primary key (OTAZKY_ID)
);

CREATE table MOZNOSTI (
    MOZNOSTI_ID   NUMBER NOT NULL,
    TEXT      VARCHAR2(500) NOT NULL,
    constraint  MOZNOSTI_PK primary key (MOZNOSTI_ID)
);

CREATE table OSOBY2 (
    OSOBY_ID    NUMBER NOT NULL,
    VEK         NUMBER NOT NULL,
    POHLAVI     VARCHAR2(4 CHAR) NOT NULL,
    VYSKA       NUMBER,
    VAHA        NUMBER,
    PRIJEM      NUMBER,
    POVOLANI_ID NUMBER NOT NULL,
    KRAJE_ID    NUMBER NOT NULL,
    constraint  OSOBY_PK primary key (OSOBY_ID)
);

ALTER TABLE OSOBY2 ADD CONSTRAINT OSOBY_FK1 
FOREIGN KEY (KRAJE_ID)
REFERENCES KRAJE (KRAJE_ID);

ALTER TABLE OSOBY2 ADD CONSTRAINT OSOBY_FK2 
FOREIGN KEY (POVOLANI_ID)
REFERENCES POVOLANI (POVOLANI_ID);

CREATE table OTAZKY_MOZNOSTI (
    OTAZKY_ID   NUMBER NOT NULL,
    MOZNOSTI_ID   NUMBER NOT NULL,
    constraint  OTAZKY_MOZNOSTI_PK primary key (OTAZKY_ID, MOZNOSTI_ID)
);

ALTER TABLE OTAZKY_MOZNOSTI ADD CONSTRAINT OTAZKY_MOZNOSTI_FK1 
FOREIGN KEY (OTAZKY_ID)
REFERENCES OTAZKY (OTAZKY_ID);

ALTER TABLE OTAZKY_MOZNOSTI ADD CONSTRAINT OTAZKY_MOZNOSTI_FK2 
FOREIGN KEY (MOZNOSTI_ID)
REFERENCES MOZNOSTI (MOZNOSTI_ID);

CREATE table ODPOVEDI (
    OTAZKY_ID   NUMBER NOT NULL,
    MOZNOSTI_ID   NUMBER NOT NULL,
    OSOBY_ID    NUMBER NOT NULL,
    constraint  ODPOVEDI_PK primary key (OTAZKY_ID, OSOBY_ID)
);

ALTER TABLE ODPOVEDI ADD CONSTRAINT ODPOVEDI_FK1 
FOREIGN KEY (OTAZKY_ID)
REFERENCES OTAZKY (OTAZKY_ID);

ALTER TABLE ODPOVEDI ADD CONSTRAINT ODPOVEDI_FK2 
FOREIGN KEY (MOZNOSTI_ID)
REFERENCES MOZNOSTI (MOZNOSTI_ID);

ALTER TABLE ODPOVEDI ADD CONSTRAINT ODPOVEDI_FK3 
FOREIGN KEY (OSOBY_ID)
REFERENCES OSOBY2 (OSOBY_ID);